### ISSUE TITLE
请问我需要修改SVG的颜色，通过什么修改呢？我用样式无法修改字体的颜色

### ISSUE THREAD

**Issue by yangjiaqiao** [bijinfeng/umi-plugin-svg-sprite#1]

**Comment by bijinfeng** [comment]
@yangjiaqiao 可以用style和className设置文字颜色，然后让svg图标颜色继承文字颜色，可以参考张鑫旭的这篇文章https://www.zhangxinxu.com/wordpress/2014/07/svg-sprites-fill-color-currentcolor/

**Comment by yangjiaqiao** [comment]
![image](https://user-images.githubusercontent.com/51978469/103185108-ecaed400-48f5-11eb-8c4c-42bc36c2aa87.png)
请问一下，通过style修改颜色，是这样写吗？
